org: caoimherice
app: food-miles
service: Food-miles

frameworkVersion: '3'

custom:
  tableName: 'users-table-${sls:stage}'
  foodTableName: 'food-table-${sls:stage}'
  wsgi:
    app: app.app

provider:
  name: aws
  httpApi:
    cors: true
  runtime: python3.9
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
            - Fn::GetAtt: [ FoodTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.tableName}
    FOOD_TABLE: ${self:custom.foodTableName}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
  apiFood:
    handler: wsgi_handler.handler
    events:
      - httpApi:
          path: /food
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
    FoodTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.foodTableName}
        AttributeDefinitions:
          - AttributeName: origin
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
